### ISSUE TITLE
Missing References

### ISSUE THREAD

**Issue by p16i** [na399/VAST-Challenge-2019-MC1#1]
There are a couple of places that references aren't linked properly. 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/1214890/61171591-2118be00-a5a4-11e9-87e1-8469e4b91e5f.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1214890/61171588-152cfc00-a5a4-11e9-9e8e-230a481fcc09.png">

<img width="893" alt="image" src="https://user-images.githubusercontent.com/1214890/61171586-ffb7d200-a5a3-11e9-8e22-d1b9d6cafcd6.png">

**Comment by na399** [comment]
Thank you. Fixed. ;)
